import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ name }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>{name.name}</h1>

        <div className={styles.grid}>


        </div>
      </main>
    </div>
  )
}

export async function getStaticProps({ params }){
  const req = await fetch(`http://localhost:3000/name.json`);
  const data = await req.json();

  return {
    props: {name : data}
  }
}